// types/task.ts
// Frontend TypeScript interfaces for Next.js 15 App Router

/**
 * Task Status Types - REMOVED 'pending'
 */
export type TaskStatus = 'in_progress' | 'completed' | 'need_help';

/**
 * Task Priority Types
 */
export type TaskPriority = 'low' | 'medium' | 'high';

/**
 * Task View Filter Types
 */

export enum TaskView {
  ALL = 'all',
  ASSIGNED_TO_ME = 'assigned-to-me',
  ASSIGNED_BY_ME = 'assigned-by-me',
}

//export type TaskView = 'all' | 'assigned-to-me' | 'assigned-by-me';

/**
 * Recurrence Frequency Types
 */
export type RecurrenceFrequency = 'daily' | 'weekly' | 'monthly' | 'quarterly' | 'yearly';

/**
 * Attachment Interface (for files and audio notes)
 */
export interface Attachment {
  fileId: string;
  filename: string;
}

/**
 * Edit History Entry
 */
export interface EditHistoryEntry {
  timestamp: number;
  editorName: string;
  description: string;
}

/**
 * Recurrence Pattern
 */
export interface RecurrencePattern {
  frequency: RecurrenceFrequency;
  interval: number;
  dayOfMonth?: number;
  endAfterOccurrences?: number;
}

/**
 * Main Task Interface (Frontend)
 * Optimized for Next.js - only includes necessary fields
 */
export interface Task {
  id: string; // Transformed from MongoDB _id
  title: string;
  description?: string;
  assignedBy: string;
  assignedTo: string;
  status: TaskStatus;
  priority: TaskPriority;
  dueDate?: string; // ISO date string (formatted to end of day)
  createdAt: string; // ISO date string (formatted to start of day)
  completedAt?: string; // ISO date string
  notes?: string;
  attachments: Attachment[];
  audioNotes: Attachment[];
  isRecurring: boolean;
  instanceNumber?: number;
  parentTaskId?: string; // Link to template
  dueDateExtensionCount: number; // NEW: Count of extensions
  // Compatibility fields for existing components if needed (will rely on strict types first)
  updatedAt?: string; 
  editHistory?: EditHistoryEntry[];
  recurrencePattern?: RecurrencePattern;
}

/**
 * Task Statistics
 */
export interface TaskStats {
  total: number;
  pending: number; // Kept for API compatibility if backend still sends it, but UI won't use it primarily
  inProgress: number;
  completed: number;
  needHelp: number;
  overdue: number;
  completionRate: number;
}

/**
 * API Response: Get Tasks
 */
export interface GetTasksResponse {
  tasks: Task[];
  total: number;
  stats: TaskStats;
  view: TaskView;
}

/**
 * API Response: Get Single Task
 */
export interface GetTaskResponse {
  task: Task;
}

/**
 * API Response: Create Task
 */
export interface CreateTaskResponse {
  message: string;
  task: Task;
}

/**
 * API Response: Update Task
 */
export interface UpdateTaskResponse {
  message: string;
  task: Task;
}

/**
 * API Response: Complete Task (with auto-generation)
 */
export interface CompleteTaskResponse {
  message: string;
  task: Task;
  nextInstance?: Task; // Auto-generated next task
  autoGenerated: boolean;
}

/**
 * API Response: Delete Task
 */
export interface DeleteTaskResponse {
  message: string;
  taskId: string;
}

/**
 * API Response: Task History
 */
export interface GetTaskHistoryResponse {
  history: EditHistoryEntry[];
}

/**
 * API Response: Recurring Stats
 */
export interface RecurringStatsResponse {
  stats: {
    total: number;
    completed: number;
    pending: number;
    inProgress: number;
    needHelp: number;
    completionRate: number;
  };
}

/**
 * API Response: Task Instances
 */
export interface GetTaskInstancesResponse {
  instances: Task[];
  count: number;
}

/**
 * API Response: Upcoming Tasks
 */
export interface GetUpcomingTasksResponse {
  instances: Task[];
  count: number;
}

/**
 * Request Body: Create Task
 */
export interface CreateTaskRequest {
  title: string;
  description?: string;
  assignedTo: string;
  status?: TaskStatus;
  priority?: TaskPriority;
  dueDate?: string; // ISO date string
  notes?: string;
  recurrencePattern?: RecurrencePattern;
}

/**
 * Request Body: Create Recurring Task
 */
export interface CreateRecurringTaskRequest {
  title: string;
  description?: string;
  assignedTo: string;
  priority?: TaskPriority;
  dueDate?: string;
  createdAt?: string;
  notes?: string;
  recurrencePattern: RecurrencePattern;
}

/**
 * Request Body: Update Task - ENHANCED
 */
export interface UpdateTaskRequest {
  title?: string;
  description?: string;
  priority?: TaskPriority;
  dueDate?: string;
  dueDateReason?: string;  // NEW: Reason for due date change
  assignedTo?: string;
  notes?: string;
  recurrencePattern?: Partial<RecurrencePattern>;  // NEW: For updating recurring tasks
  status?: TaskStatus;
}

/**
 * Request Body: Extend Due Date - NEW
 */
export interface ExtendDueDateRequest {
  newDueDate: string;  // ISO date string
  reason?: string;
}

/**
 * Request Body: Update Status
 */
export interface UpdateStatusRequest {
  status: TaskStatus;
  notes?: string;
}

/**
 * Request Body: Add Attachment/Audio Note
 */
export interface AddAttachmentRequest {
  fileId: string;
  filename: string;
}

/**
 * Request Body: Update Recurrence Pattern
 */
export interface UpdateRecurrencePatternRequest {
  pattern: Partial<RecurrencePattern>;
}

/**
 * Request Body: Convert to Recurring
 */
export interface ConvertToRecurringRequest {
  pattern: RecurrencePattern;
}

/**
 * Query Parameters: Get Tasks
 */
export interface GetTasksParams {
  status?: TaskStatus;
  priority?: TaskPriority;
  search?: string;
  view?: TaskView;
  includeHidden?: boolean;
}

/**
 * Query Parameters: Get Instances
 */
export interface GetInstancesParams {
  status?: TaskStatus;
  limit?: number;
  includeHidden?: boolean;
}

/**
 * Query Parameters: Get Upcoming
 */
export interface GetUpcomingParams {
  daysAhead?: number;
}

/**
 * API Error Response
 */
export interface ApiError {
  error: string;
  details?: string;
}

// Additional helper types for UI components (Users, UploadedFile)
export interface Users {
    id: string;
    name: string;
    avatar: string;
    role?: string; // Added optional role
}

export interface UploadedFile {
    fileId: string;
    filename: string;
    url: string;
}

// For existing code compatibility aliases
export type CreateTaskInput = CreateTaskRequest;
export type UpdateTaskInput = UpdateTaskRequest;

// ============================================
// HELPER FUNCTIONS FOR FRONTEND
// ============================================

/**
 * Check if task is overdue
 */
export function isTaskOverdue(task: Task): boolean {
  if (!task.dueDate || task.status === 'completed') return false;
  return new Date(task.dueDate) < new Date();
}

/**
 * Get task status color (for UI) - UPDATED
 */
export function getTaskStatusColor(status: TaskStatus): string {
  switch (status) {
    case 'completed':
      return 'green';
    case 'in_progress':
      return 'blue';
    case 'need_help':
      return 'red';
    default:
      return 'gray';
  }
}

/**
 * Get priority color (for UI)
 */
export function getTaskPriorityColor(priority: TaskPriority): string {
  switch (priority) {
    case 'high':
      return 'red';
    case 'medium':
      return 'yellow';
    case 'low':
    default:
      return 'green';
  }
}

/**
 * Format date for display
 */
export function formatTaskDate(dateString?: string): string {
  if (!dateString) return 'No date';
  
  const date = new Date(dateString);
  const now = new Date();
  const diffMs = date.getTime() - now.getTime();
  const diffDays = Math.floor(diffMs / (1000 * 60 * 60 * 24));

  if (diffDays === 0) return 'Today';
  if (diffDays === 1) return 'Tomorrow';
  if (diffDays === -1) return 'Yesterday';
  if (diffDays > 0 && diffDays < 7) return `In ${diffDays} days`;
  if (diffDays < 0 && diffDays > -7) return `${Math.abs(diffDays)} days ago`;

  return date.toLocaleDateString();
}

/**
 * Get time until due
 */
export function getTimeUntilDue(task: Task): string {
  if (!task.dueDate) return '';
  if (task.status === 'completed') return 'Completed';

  const now = new Date();
  const due = new Date(task.dueDate);
  const diffMs = due.getTime() - now.getTime();
  const diffHours = Math.floor(diffMs / (1000 * 60 * 60));
  const diffDays = Math.floor(diffHours / 24);

  if (diffMs < 0) return 'Overdue';
  if (diffHours < 1) return 'Due soon';
  if (diffHours < 24) return `${diffHours}h left`;
  return `${diffDays}d left`;
}

/**
 * Sort tasks by priority and due date
 */
export function sortTasks(tasks: Task[]): Task[] {
  const priorityOrder = { high: 0, medium: 1, low: 2 };

  return [...tasks].sort((a, b) => {
    // First by priority
    const priorityDiff = priorityOrder[a.priority] - priorityOrder[b.priority];
    if (priorityDiff !== 0) return priorityDiff;

    // Then by due date
    if (a.dueDate && b.dueDate) {
      return new Date(a.dueDate).getTime() - new Date(b.dueDate).getTime();
    }
    if (a.dueDate) return -1;
    if (b.dueDate) return 1;

    // Finally by created date
    return new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime();
  });
}

/**
 * Filter tasks by search query
 */
export function filterTasksBySearch(tasks: Task[], query: string): Task[] {
  if (!query.trim()) return tasks;

  const lowercaseQuery = query.toLowerCase();
  return tasks.filter(
    task =>
      task.title.toLowerCase().includes(lowercaseQuery) ||
      task.description?.toLowerCase().includes(lowercaseQuery) ||
      task.notes?.toLowerCase().includes(lowercaseQuery)
  );
}

/**
 * Group tasks by status - UPDATED
 */
export function groupTasksByStatus(tasks: Task[]): Record<TaskStatus, Task[]> {
  const initial: Record<TaskStatus, Task[]> = {
    in_progress: [],
    completed: [],
    need_help: []
  };

  return tasks.reduce(
    (acc, task) => {
      // Handle potentially old status 'pending' by ignoring or mapping if necessary. 
      // The type definition says 'pending' is REMOVED, but existing data might still have it.
      // We will only group valid statuses.
      if (task.status in acc) {
        acc[task.status].push(task);
      }
      return acc;
    },
    initial
  );
}
